name: Compile

on:
  push:
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        run: make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: CVE-2019-2215
          path: ./cve-2019-2215
